image: archlinux
packages:
  - python-pip
  - python-wheel
  - twine
secrets:
  - 55e5a7f3-0b90-4196-b002-1a81cc9d1650
tasks:
  - build: |
      cd aiohttp-oauthlib
      python setup.py sdist bdist_wheel
      git describe --exact-match --tags || complete-build
  - publish: |
      cd aiohttp-oauthlib
      twine upload dist/*
